.PHONY : ALL
ALL :  boiling ftoc t2.3.1 t2.3.2 t2.3.3 t2.3.4 t2.4.1 t2.4 t2.5

boiling:
	go build boiling.go
ftoc:
	go build ftoc.go
t2.3.1:
	go build t2.3.1.go
t2.3.2:
	go build t2.3.2.go
t2.3.3:
	go build t2.3.3.go
t2.3.4:
	go build t2.3.4.go
t2.4.1:
	go build t2.4.1.go
t2.4:
	go build t2.4.go
t2.5:
	go build t2.5.go

.PHONY : clean
clean :
	 rm -rf  boiling ftoc t2.3.1 t2.3.2 t2.3.3 t2.3.4 t2.4.1 t2.4 t2.5
