.PHONY : ALL
ALL :  boiling ftoc t2.3.1 t2.3.2

boiling:
	go build boiling.go
ftoc:
	go build ftoc.go
t2.3.1:
	go build t2.3.1.go
t2.3.2:
	go build t2.3.2.go

.PHONY : clean
clean :
	 rm -rf  boiling ftoc t2.3.1 t2.3.2
