.PHONY : ALL
ALL :  t3.5.1 t3.5.3 t3.5.4 t3.5.5 t3.5

t3.5.1:
	go build t3.5.1.go
t3.5.3:
	go build t3.5.3.go
t3.5.4:
	go build t3.5.4.go
t3.5.5:
	go build t3.5.5.go
t3.5:
	go build t3.5.go

.PHONY : clean
clean :
	 rm -rf  t3.5.1 t3.5.3 t3.5.4 t3.5.5 t3.5
