.PHONY : ALL
ALL :  e1.1 echo1 echo2 echo3 echo4 helloworld

e1.1 :
	go build e1.1.go

echo1 :
	go build echo1.go

echo2 :
	go build echo2.go

echo3 :
	go build echo3.go

echo4 :
	go build echo4.go

helloworld :
	go build helloworld.go

.PHONY : clean
clean:
	rm -rf  e1.1 echo1 echo2 echo3 echo4 helloworld
