.PHONY : ALL
ALL :  echo1 echo2 echo3 echo4 helloworld

echo1 :
	go build echo1.go

echo2 :
	go build echo2.go

echo3 :
	go build echo3.go

echo4 :
	go build echo4.go

helloworld :
	go build helloworld.go

.PHONY : clean
clean:
	rm -rf  echo1 echo2 echo3 echo4 helloworld
